from __future__ import annotations

from utils.env_config import get_data_yaml, get_dataset_dir, get_device, get_hyp_file, get_output_dir, get_weights
from tools.gui_panel.schemas import FieldSpec, TaskSpec


def _choice(value: str, label: str) -> dict[str, str]:
    return {"value": value, "label": label}


COMMON_GROUPS = [
    {"id": "basic", "label": "基础输入"},
    {"id": "output", "label": "输出配置"},
    {"id": "advanced", "label": "高级参数"},
]


TASK_SPECS: dict[str, TaskSpec] = {
    "train": TaskSpec(
        task_type="train",
        display_name="Train",
        description="Run train.py through run_with_log.py.",
        field_groups=COMMON_GROUPS,
        fields=[
            FieldSpec("data", "Data YAML", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="数据集配置文件路径，定义训练/验证集路径及类别信息"),
            FieldSpec("weights", "Weights", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="预训练权重文件路径，支持 .pt 格式"),
            FieldSpec("project", "Project", "path", "output", required=True, browsable=True, browse_kind="directory",
                      help_text="训练结果输出根目录，默认为 runs/train"),
            FieldSpec("name", "Run Name", "text", "output", required=True,
                      help_text="本次训练运行的名称，输出将保存到 project/name 下"),
            FieldSpec("device", "Device", "text", "advanced", required=True,
                      help_text="训练设备，如 0 表示 GPU 0，cpu 表示 CPU"),
            FieldSpec("epochs", "Epochs", "number", "advanced", required=True,
                      help_text="训练总轮数，一个 epoch 表示完整遍历一次训练集"),
            FieldSpec("batch_size", "Batch Size", "number", "advanced", required=True,
                      help_text="每批处理的图像数量，受限于 GPU 显存大小"),
            FieldSpec("imgsz", "Image Size", "number", "advanced", required=True,
                      help_text="训练时输入图像的尺寸（像素），所有图像会被缩放至此尺寸"),
            FieldSpec("workers", "Workers", "number", "advanced", required=True,
                      help_text="数据加载的并行工作进程数"),
            FieldSpec("seed", "Seed", "number", "advanced", required=True,
                      help_text="随机种子，固定后可保证训练结果可复现"),
            FieldSpec("patience", "Patience", "number", "advanced", required=True,
                      help_text="早停耐心值：连续 N 个 epoch 无提升则提前终止训练"),
            FieldSpec("optimizer", "Optimizer", "select", "advanced", required=True,
                      choices=[_choice("SGD", "SGD"), _choice("Adam", "Adam"), _choice("AdamW", "AdamW")],
                      help_text="优化器类型：SGD 更稳定，Adam/AdamW 收敛更快"),
            FieldSpec("exist_ok", "Exist OK", "checkbox", "advanced",
                      help_text="允许覆盖已存在的同名输出目录"),
            FieldSpec("amp_mode", "AMP", "select", "advanced", required=True,
                      choices=[_choice("auto", "Auto"), _choice("on", "On"), _choice("off", "Off")],
                      help_text="自动混合精度训练：可节省显存并加速训练"),
            FieldSpec("resume", "Resume", "checkbox", "advanced",
                      help_text="从上次中断处恢复训练，会加载最近的 checkpoint"),
            FieldSpec("hyp", "Hyp YAML", "path", "advanced", browsable=True, browse_kind="file",
                      help_text="超参数配置文件路径，控制学习率、数据增强等超参数"),
            FieldSpec("cfg", "Model CFG", "path", "advanced", browsable=True, browse_kind="file",
                      help_text="模型结构配置文件（.yaml），通常使用默认即可"),
        ],
        defaults={
            "data": get_data_yaml(),
            "weights": get_weights(),
            "project": get_output_dir("train"),
            "name": "panel_train",
            "device": get_device(),
            "epochs": 70,
            "batch_size": 4,
            "imgsz": 640,
            "workers": 2,
            "seed": 0,
            "patience": 20,
            "optimizer": "SGD",
            "exist_ok": False,
            "amp_mode": "off",
            "resume": False,
            "hyp": get_hyp_file(),
            "cfg": "",
            "extra_args": "",
        },
    ),
    "detect": TaskSpec(
        task_type="detect",
        display_name="Detect",
        description="Run detect.py through run_with_log.py.",
        field_groups=COMMON_GROUPS,
        fields=[
            FieldSpec("weights", "Weights", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="训练好的模型权重文件路径"),
            FieldSpec("source", "Source", "path", "basic", required=True, browsable=True, browse_kind="directory",
                      help_text="推理输入源：可以是图片/视频目录或单个文件路径"),
            FieldSpec("data", "Data YAML", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="数据集配置文件，包含类别名称和数量信息"),
            FieldSpec("project", "Project", "path", "output", required=True, browsable=True, browse_kind="directory",
                      help_text="检测结果输出根目录"),
            FieldSpec("name", "Run Name", "text", "output", required=True,
                      help_text="本次检测运行的名称，结果将保存在 project/name 下"),
            FieldSpec("device", "Device", "text", "advanced", required=True,
                      help_text="推理设备，如 0 表示 GPU 0"),
            FieldSpec("imgsz", "Image Size", "number", "advanced", required=True,
                      help_text="推理时输入图像的尺寸（像素）"),
            FieldSpec("conf_thres", "Conf Threshold", "number", "advanced", required=True, step="0.1",
                      help_text="置信度阈值：低于此值的检测框将被过滤，取值范围 0~1"),
            FieldSpec("iou_thres", "IoU Threshold", "number", "advanced", required=True, step="0.1",
                      help_text="NMS 的 IoU 阈值：高于此重叠比例的重叠框将被去除，取值范围 0~1"),
            FieldSpec("view_img", "View Image", "checkbox", "advanced",
                      help_text="实时显示检测结果窗口"),
            FieldSpec("save_txt", "Save TXT", "checkbox", "advanced",
                      help_text="将检测结果保存为 YOLO 格式的 .txt 标签文件"),
            FieldSpec("save_conf", "Save Conf", "checkbox", "advanced",
                      help_text="在保存的 TXT 结果中附带置信度分数"),
            FieldSpec("nosave", "No Save Media", "checkbox", "advanced",
                      help_text="不保存检测后的图片/视频文件"),
            FieldSpec("save_img_frames", "Save VOC Frames", "checkbox", "advanced",
                      help_text="按帧导出检测结果，用于 VOC 数据集构建"),
            FieldSpec("vid_stride", "Video Stride", "number", "advanced", required=True,
                      help_text="视频抽帧步长：每隔 N 帧进行一次检测"),
            FieldSpec("voc_root", "VOC Root", "path", "advanced", browsable=True, browse_kind="directory",
                      help_text="VOC 格式数据集的根目录，与 incremental_mp4 配合使用"),
            FieldSpec("incremental_mp4", "Incremental MP4", "checkbox", "advanced",
                      help_text="增量式生成 VOC MP4 文件，仅处理新增帧"),
            FieldSpec("classes", "Classes", "text", "advanced", placeholder="e.g. 0,1",
                      help_text="仅检测指定类别，用逗号分隔类别编号"),
            FieldSpec("exist_ok", "Exist OK", "checkbox", "advanced",
                      help_text="允许覆盖已存在的同名输出目录"),
        ],
        defaults={
            "weights": get_weights(),
            "source": "",
            "data": get_data_yaml(),
            "project": get_output_dir("detect"),
            "name": "voc_stride10",
            "device": get_device(),
            "imgsz": 640,
            "conf_thres": 0.25,
            "iou_thres": 0.45,
            "view_img": False,
            "save_txt": False,
            "save_conf": False,
            "nosave": True,
            "save_img_frames": True,
            "vid_stride": 10,
            "voc_root": get_dataset_dir(),
            "incremental_mp4": True,
            "classes": "",
            "exist_ok": False,
            "extra_args": "",
        },
    ),
    "val": TaskSpec(
        task_type="val",
        display_name="Val",
        description="Run val.py through run_with_log.py.",
        field_groups=COMMON_GROUPS,
        fields=[
            FieldSpec("data", "Data YAML", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="数据集配置文件路径"),
            FieldSpec("weights", "Weights", "path", "basic", required=True, browsable=True, browse_kind="file",
                      help_text="待评估的模型权重文件路径"),
            FieldSpec("project", "Project", "path", "output", required=True, browsable=True, browse_kind="directory",
                      help_text="验证结果输出根目录"),
            FieldSpec("name", "Run Name", "text", "output", required=True,
                      help_text="本次验证运行的名称"),
            FieldSpec("device", "Device", "text", "advanced", required=True,
                      help_text="评估设备，如 0 表示 GPU 0"),
            FieldSpec("batch_size", "Batch Size", "number", "advanced", required=True,
                      help_text="每批处理的图像数量"),
            FieldSpec("imgsz", "Image Size", "number", "advanced", required=True,
                      help_text="评估时输入图像的尺寸（像素）"),
            FieldSpec("conf_thres", "Conf Threshold", "number", "advanced", required=True, step="0.1",
                      help_text="置信度阈值：低于此值的检测结果将被忽略，取值范围 0~1"),
            FieldSpec("iou_thres", "IoU Threshold", "number", "advanced", required=True, step="0.1",
                      help_text="NMS 的 IoU 阈值：控制重叠框的去重程度，取值范围 0~1"),
            FieldSpec("task", "Task", "select", "advanced", required=True,
                      choices=[_choice("val", "val"), _choice("test", "test"), _choice("speed", "speed"), _choice("study", "study")],
                      help_text="评估模式：val 验证集 / test 测试集 / speed 测速 / study 参数研究"),
            FieldSpec("workers", "Workers", "number", "advanced", required=True,
                      help_text="数据加载的并行工作进程数"),
            FieldSpec("save_txt", "Save TXT", "checkbox", "advanced",
                      help_text="将验证结果保存为 TXT 文件"),
            FieldSpec("save_json", "Save JSON", "checkbox", "advanced",
                      help_text="将验证结果保存为 JSON 文件"),
            FieldSpec("half", "Half Precision", "checkbox", "advanced",
                      help_text="使用 FP16 半精度推理，可加速但精度略降"),
            FieldSpec("dnn", "OpenCV DNN", "checkbox", "advanced",
                      help_text="使用 OpenCV DNN 模块进行推理"),
            FieldSpec("exist_ok", "Exist OK", "checkbox", "advanced",
                      help_text="允许覆盖已存在的同名输出目录"),
        ],
        defaults={
            "data": get_data_yaml(),
            "weights": get_weights(),
            "project": get_output_dir("val"),
            "name": "panel_val",
            "device": get_device(),
            "batch_size": 4,
            "imgsz": 640,
            "conf_thres": 0.001,
            "iou_thres": 0.6,
            "task": "val",
            "workers": 2,
            "save_txt": False,
            "save_json": False,
            "half": False,
            "dnn": False,
            "exist_ok": False,
            "extra_args": "",
        },
    ),
    "fiftyone": TaskSpec(
        task_type="fiftyone",
        display_name="FiftyOne",
        description="Import a VOC dataset into FiftyOne.",
        field_groups=COMMON_GROUPS,
        fields=[
            FieldSpec("mode", "Mode", "select", "basic", required=True,
                      choices=[_choice("dataset_root_auto", "Dataset Root Auto"), _choice("explicit_voc", "Explicit VOC Paths")],
                      help_text="导入模式：自动从 dataset_root 推断路径 / 手动指定 VOC 路径"),
            FieldSpec("dataset_name", "Dataset Name", "text", "basic", required=True,
                      help_text="在 FiftyOne 中创建的数据集名称"),
            FieldSpec("dataset_root", "Dataset Root", "path", "basic", browsable=True, browse_kind="directory",
                      visible_when={"mode": "dataset_root_auto"},
                      help_text="数据集根目录，程序将自动推断 data/labels 子目录"),
            FieldSpec("data_dir", "Data Dir", "path", "basic", browsable=True, browse_kind="directory",
                      visible_when={"mode": "explicit_voc"},
                      help_text="VOC 数据目录（包含图像文件）"),
            FieldSpec("labels_dir", "Labels Dir", "path", "basic", browsable=True, browse_kind="directory",
                      visible_when={"mode": "explicit_voc"},
                      help_text="VOC 标签目录（包含 XML 标注文件）"),
            FieldSpec("overwrite", "Overwrite Existing", "checkbox", "advanced",
                      help_text="覆盖 FiftyOne 中已存在的同名数据集"),
            FieldSpec("label_field", "Label Field", "text", "advanced", required=True,
                      help_text="FiftyOne 中存储标签的字段名称，默认为 ground_truth"),
            FieldSpec("launch_app", "Launch App", "checkbox", "advanced",
                      help_text="导入完成后自动启动 FiftyOne 可视化应用"),
        ],
        defaults={
            "mode": "dataset_root_auto",
            "dataset_name": "panel_dataset",
            "dataset_root": "",
            "data_dir": "",
            "labels_dir": "",
            "overwrite": True,
            "label_field": "ground_truth",
            "launch_app": True,
            "extra_args": "",
        },
    ),
}
