#!/usr/bin/env bash
set -euo pipefail

SOURCE_ROOT="${SOURCE_ROOT:-/root/.agents/skills/skills}"
MANAGER_ROOT="${MANAGER_ROOT:-${SOURCE_ROOT}/skills-unification-manager}"
MANIFEST_PATH="${MANIFEST_PATH:-${MANAGER_ROOT}/custom-skills.txt}"
AUTH_ROOT="${AUTH_ROOT:-/root/.cc-switch/skills/skills}"
AGENTS_MIRROR_ROOT="${AGENTS_MIRROR_ROOT:-/root/.agents/skills}"
REGISTRY_PATH="${REGISTRY_PATH:-${AGENTS_MIRROR_ROOT}/MY_CREATED_SKILLS.md}"
RECORD_PATH="${RECORD_PATH:-/root/.cc-switch/SKILLS_UNIFIED_LIST.md}"
TIMESTAMP="$(date +%Y%m%d%H%M%S)"

MIRROR_ROOTS=(
  "/root/.claude/skills"
  "/root/.cursor/skills"
  "/root/.gemini/skills"
  "/root/.opencode/skills"
  "/root/.qwen/skills"
  "/root/.trae/skills"
)

INVENTORY_ONLY_ROOTS=(
  "/root/.codex/skills"
)

fail() {
  echo "error: $*" >&2
  exit 1
}

require_text() {
  local file="$1"
  local pattern="$2"
  if ! grep -Fq "$pattern" "$file"; then
    fail "missing required text '$pattern' in $file"
  fi
}

copy_tree() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  if [[ -e "$dest" || -L "$dest" ]]; then
    rm -rf "$dest"
  fi
  cp -a "$src" "$dest"
}

backup_path() {
  local path="$1"
  local backup="${path}.bak.${TIMESTAMP}"
  mv "$path" "$backup"
  echo "backed up $path -> $backup"
}

ensure_root_symlink() {
  local link_path="$1"
  local target="$2"

  mkdir -p "$(dirname "$link_path")"

  if [[ -L "$link_path" ]]; then
    local current
    current="$(readlink -f "$link_path" || true)"
    if [[ "$current" == "$(readlink -f "$target")" ]]; then
      return
    fi
    rm -f "$link_path"
  elif [[ -e "$link_path" ]]; then
    backup_path "$link_path"
  fi

  ln -s "$target" "$link_path"
  echo "linked $link_path -> $target"
}

ensure_skill_link() {
  local root="$1"
  local name="$2"
  local target="$3"
  local link_path="${root}/${name}"

  mkdir -p "$root"

  if [[ -L "$link_path" ]]; then
    local current
    current="$(readlink -f "$link_path" || true)"
    if [[ "$current" == "$(readlink -f "$target")" ]]; then
      return
    fi
    rm -f "$link_path"
  elif [[ -e "$link_path" ]]; then
    backup_path "$link_path"
  fi

  ln -s "$target" "$link_path"
  echo "linked $link_path -> $target"
}

[[ -d "$SOURCE_ROOT" ]] || fail "source root not found: $SOURCE_ROOT"
[[ -f "$MANIFEST_PATH" ]] || fail "manifest not found: $MANIFEST_PATH"
mkdir -p "$AUTH_ROOT" "$AGENTS_MIRROR_ROOT"

mapfile -t SKILLS < <(awk 'NF && $1 !~ /^#/' "$MANIFEST_PATH")
[[ "${#SKILLS[@]}" -gt 0 ]] || fail "manifest is empty: $MANIFEST_PATH"

for name in "${SKILLS[@]}"; do
  src_dir="${SOURCE_ROOT}/${name}"
  src_skill="${src_dir}/SKILL.md"

  [[ -d "$src_dir" ]] || fail "listed skill directory missing: $src_dir"
  [[ -f "$src_skill" ]] || fail "listed skill missing SKILL.md: $src_skill"
  require_text "$src_skill" "name: ${name}"
  require_text "$src_skill" "custom: true"
  require_text "$src_skill" "sync_to_agents: true"

  copy_tree "$src_dir" "${AUTH_ROOT}/${name}"
  copy_tree "$src_dir" "${AGENTS_MIRROR_ROOT}/${name}"
done

for root in "${MIRROR_ROOTS[@]}"; do
  ensure_root_symlink "$root" "$AUTH_ROOT"
done

for root in "${INVENTORY_ONLY_ROOTS[@]}"; do
  mkdir -p "$root"
  for name in "${SKILLS[@]}"; do
    ensure_skill_link "$root" "$name" "${AUTH_ROOT}/${name}"
  done
done

{
  echo "# My Created Skills"
  echo
  echo "Generated by Linux skills unification."
  echo "Editable source payload used for this run: \`${SOURCE_ROOT}\`"
  echo "Authoritative root: \`${AUTH_ROOT}\`"
  echo
  for name in "${SKILLS[@]}"; do
    echo "- \`${name}\`"
  done
} > "$REGISTRY_PATH"

{
  echo "# Skills Maintenance Record"
  echo
  echo "## Authoritative Root"
  echo
  echo "- \`${AUTH_ROOT}\`"
  echo
  echo "## Generated Outputs"
  echo
  echo "- Managed-skill manifest: \`${MANIFEST_PATH}\`"
  echo "- Agents mirror: \`${AGENTS_MIRROR_ROOT}\`"
  echo "- Registry: \`${REGISTRY_PATH}\`"
  echo
  echo "## User-Level Mirror Roots"
  echo
  for root in "${MIRROR_ROOTS[@]}"; do
    echo "- \`${root}\` -> \`${AUTH_ROOT}\`"
  done
  echo
  echo "## Inventory-Only Roots"
  echo
  for root in "${INVENTORY_ONLY_ROOTS[@]}"; do
    echo "- \`${root}\`"
  done
  echo
  echo "## Managed Skills"
  echo
  for name in "${SKILLS[@]}"; do
    echo "- \`${name}\`"
  done
} > "$RECORD_PATH"

echo "Unified ${#SKILLS[@]} managed skills."
echo "Source root: ${SOURCE_ROOT}"
echo "Authoritative root: ${AUTH_ROOT}"
echo "Agents mirror: ${AGENTS_MIRROR_ROOT}"
